CREATE TABLE rates (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    currency VARCHAR(5) NOT NULL,
    rate DOUBLE(15) NOT NULL,
);

CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(200) NOT NULL,
);

CREATE TABLE details (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    last_date VARCHAR(50) NOT NULL,
    last_time VARCHAR(200) NOT NULL,
);