CREATE TABLE rates (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    currency VARCHAR(5) NOT NULL,
    rate DOUBLE(15) NOT NULL,
);

CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username VARCHAR(50) NOT NULL,
    password_ VARCHAR(200) NOT NULL,
);

CREATE TABLE details (
    pk_id TINYINT NOT NULL DEFAULT 1,
    CONSTRAINT id INTEGER PRIMARY KEY (pk_id),
    last_updated VARCHAR(50) NOT NULL CHECK,
    timezone VARCHAR(50) NOT NULL,
    CONSTRAINT single_row CHECK(pk_id=1),
);
